blank_issues_enabled: true
contact_links:
  - name: Questions and Discussions
    url: https://github.com/kroxylicious/kroxylicious-junit5-extension/discussions
    about: Please ask and discuss questions here.
